package:
  name: h5spark
  version: "0.1"

source:
  git_rev: master
  git_url: https://github.com/mganta/h5spark.git

requirements:
  host:
    - python
    - setuptools
    - nose

  run:
    - python

test:
  imports: 
    - h5spark

about:
  home: https://github.com/mganta/h5spark
  license: Apache
  license_file: LICENSE
