package:
  name: h5spark
  version: latest

source:
  git_rev: latest
  git_url: https://github.com/mganta/h5py-install.git

requirements:
  host:
    - python
    - setuptools

  run:
    - python

test:
  imports: 
    - h5spark

about:
  home: https://github.com/mganta/h5py-install
  license: Apache
  license_file: LICENSE
